# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d67ec6a487160eab48704cd1a2fc1bfe590175b0c24d6ff2ea087d136746649b201d623ca99f4117ffe7d060963d9a007642af24b026f0a307752be1a00d7ee

test:
  secret_key_base: b25e1d0fbe8bca72c1e948779311f64d7b9ecd58825de9b57a85d9356ac477586fed535475ea06ffe570fe091fa462544a7d594a4ce041b729104dfa0fd167c6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
